name: Deploy Backend to ConoHa VPS Prod02 Server

on:
  pull_request:
    types: [labeled]

jobs:
  deploy_to_prod02_backend:
    runs-on: ubuntu-latest
    if: |
      ((github.event.action == 'labeled') &&
        (github.event.label.name == 'deploy_prod02')) ||
      ((github.event.action == 'synchronize') &&
        contains(github.event.pull_request.labels.*.name, 'deploy_prod02'))
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.TENNISLOG_SSH_PRIVATE_KEY }}
          host: ${{ secrets.PROD02_HOST_IP }}
          username: ${{ secrets.PROD02_SSH_USER }}
          port: ${{ secrets.PROD02_SSH_PORT }}
          script: |
            cd ./tennis_log_api
            git pull origin main

      - name: cache vendor
        id: cache
        uses: actions/cache@v1
        with:
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: composer install
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install -n --prefer-dist
